services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\CollectWlanMacBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources,Tests}'
